#define MODEL_Root              0x3A
#define MODEL_Bridge10          0x39
#define MODEL_BridgeTop10       0x38
#define MODEL_Bridge9           0x37
#define MODEL_BridgeTop9        0x36
#define MODEL_Bridge8           0x35
#define MODEL_BridgeTop8        0x34
#define MODEL_Bridge7           0x33
#define MODEL_BridgeTop7        0x32
#define MODEL_Bridge6           0x31
#define MODEL_BridgeTop6        0x30
#define MODEL_Bridge5           0x2F
#define MODEL_BridgeTop5        0x2E
#define MODEL_Bridge4           0x2D
#define MODEL_BridgeTop4        0x2C
#define MODEL_Bridge3           0x2B
#define MODEL_BridgeTop3        0x2A
#define MODEL_Bridge2           0x29
#define MODEL_BridgeTop2        0x28
#define MODEL_Bridge1           0x27
#define MODEL_BridgeTop1        0x26
#define MODEL_AxeGroup          0x25
#define MODEL_Axe               0x24
#define MODEL_Models            0x23
#define MODEL_AxePlatform       0x22
#define MODEL_ChainHook         0x21
#define MODEL_AxeChain          0x20
#define MODEL_Lava              0x1F
#define MODEL_LavaFlowBG        0x1E
#define MODEL_LavaFlowR         0x1D
#define MODEL_LavaFlowL         0x1C
#define MODEL_StageWallFront    0x1B
#define MODEL_SideWallR4        0x1A
#define MODEL_SideWallR3        0x19
#define MODEL_SideWallR2        0x18
#define MODEL_SideWallR1        0x17
#define MODEL_FrontWallR2       0x16
#define MODEL_FrontWallR1       0x15
#define MODEL_FloorRight        0x14
#define MODEL_SideWallL2        0x13
#define MODEL_SideWallL1        0x12
#define MODEL_FrontWallL2       0x11
#define MODEL_FrontWallL1       0x10
#define MODEL_FloorLeft         0xF
#define MODEL_BowserStatuePodium 0xE
#define MODEL_BowserStatueSupport 0xD
#define MODEL_StageWallFront    0xC
#define MODEL_BowserStatueBust  0xB
#define MODEL_StageWallSide     0xA
#define MODEL_StageWallFront    0x9
#define MODEL_CeilingBricks     0x8
#define MODEL_Rails             0x7
#define MODEL_BrickFloorBack    0x6
#define MODEL_BackWall          0x5
#define MODEL_Pillar5           0x4
#define MODEL_Pillar4           0x3
#define MODEL_Pillar3           0x2
#define MODEL_Pillar2           0x1
#define MODEL_Pillar1           0x0

