#message:2F:(TrainLobby_CutsceneTest)
{
	[Style Right]
	Test.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadsworthInteract)
{
	[Style Right]
	Have you made your[BR]
	preparations, Master Mario?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadsworthInteractNo)
{
	[Style Right]
	You must hurry Master Mario![BR]
	Every moment the princess[BR]
	is unsafe, we risk certain doom![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadsworthInteractYes)
{
	[Style Right]
	Excellent! Make haste[BR]
	and venture forth![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadsworthStartBoss)
{
	[Style Right]
	Quickly now! Tally-ho! Early[BR]
	buzzard gets the spoils! You've[BR]got this! Protect the princess![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BubbaInteract)
{
	[Style Right]
	She told me that I would be in[BR]
	the pan 10 minutes ago![BR]
	[Wait][Next]
	Unbelievable.
	[Wait][End]
}



#message:2F:(TrainLobby_ToadMinisterInteract)
{
	[Style Right]
	I have faith in you Mario,[BR]
	oust those ne'er-do-wells![BR]
	[Wait][Next]
	I'll stay here and keep the lunch[BR]
	safe and sound.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_LuigiInteract)
{
	[Style Inspect]
	He's in a deep sleep, not even[BR]
	the dead could wake him.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_KammyInteract)
{
	[Style Right]
	Nyeah heh heh... not so fast![BR]
	[Pause 5]Turn around nice and slowly...[BR]
	[Wait][Next]
	You don't want to know what[BR]
	I'm packing in here![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_PeachInteract)
{
	[Style Right]
	Hi Mario how can I help you?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_MapTattle)
{
	[Style tattle]
	[EnableCDownNext]I can't believe they found us here,[BR]
	I guess even a trip on Steamer[BR]
	isn't discreet enough...[BR]
	[Wait][Next]
	It's so nice in here though, it almost[BR]
	makes me forget about the[BR]
	danger outside.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_TayceTTattle)
{
	[Style tattle]
	[EnableCDownNext]She's Tayce T., by far the[BR]
	greatest cook around.[BR]
	[Wait][Next]
	It seems like she's really busy[BR]
	right now though...[BR]
	[Pause 10]Maybe she can still help us?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_CalamityKammyTattle)
{
	[Style tattle]
	[EnableCDownNext]That's Calamity Kammy, the nastiest[BR]
	sharpshooter in the Koopa Gang![BR]
	[Wait][Next]
	I heard she taught Koopa the Kid[BR]
	all he knows about firepower.[BR]
	[Wait][Next]
	I wouldn't mess with her right now,[BR]
	let's just walk away.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BigBubbaTattle)
{
	[Style tattle]
	[EnableCDownNext]That's a.. Big Bubba?! [BR]
	What's he doing all the way out here?[BR]
	[Wait][Next]
	Hm...[Pause 10] Well I guess as long as he's[BR]
	not hungry we don't have to[BR]
	worry, we're safe.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadMinisterTattle)
{
	[Style tattle]
	[EnableCDownNext]This is the Toad Minister.[BR]
	[Wait][Next]
	Uh...[Pause 10] he doesn't seem too concerned[BR]
	with the situation outside.[BR]
	[Wait][Next]
	I haven't seen him eat since we left,[BR]
	he must be pretty hungry right now.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_LuigiTattle)
{
	[Style tattle]
	[EnableCDownNext]He's Luigi.[BR]
	[Pause 5]I don't have to say anything[BR]
	about him, do I? He's your[BR]
	brother![BR]
	[Wait][Next]
	...[Pause 10]He should be helping us[BR]
	though, shouldn't he?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_PeachTattle)
{
	[Style tattle]
	[EnableCDownNext]Come on Mario, you know who[BR]
	Princess Peach is![BR]
	[Wait][Next]
	[Pause 10]...Oh? Maybe you're testing me[BR]
	right now?[BR]
	[Wait][Next]
	I'm happy to play along[BR]
	but we really should be getting[BR]
	ready right now.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadTattle)
{
	[Style tattle]
	[EnableCDownNext]That's Toad, he's been traveling[BR]
	with the princess for a while now. [BR]
	[Wait][Next]
	It's his responsibility to watch the[BR]
	Badge shipment being delivered.[BR]
	[Wait][Next]
	He should be alright with you[BR]
	borrowing some, go ahead and ask![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_ToadsworthTattle)
{
	[Style tattle]
	[EnableCDownNext]That's Toadsworth, he's been with[BR]
	the princess for years as[BR]
	her steward.[BR]
	[Wait][Next]
	He's very adamant about ensuring[BR]
	the safety and security of the[BR]
	princess at all times.[BR]
	[Wait][Next]
	I would stop staring at him and[BR]
	get ready, he's looking very worried[BR]
	at the moment.[BR]
	[Wait][End]
}



#message:2F:(Menu_MenuBuy)
{
	Buy which one?[End]
}


#message:2F:(MenuTip_Item)
{
	Item[End]
}


#message:2F:(TrainLobby_BorrowToad1)
{
	[Style right]
	Mario! Are you really going out[BR]
	there? You should take some of[BR]
	these badges we're delivering,[BR]
	they could really come in handy![BR]
	[Wait][Next]
	Just leave some Star Pieces[BR]
	with me just in case something[BR]
	happens to them out there if you[BR]
	don't mind.[BR]
	[Wait][Next]
	Will you borrow some badges?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BorrowToad2)
{
	[Style right]
	You want to take[BR]
	"[Var 0]" for[BR]
	[Var 1] Star Pieces.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BorrowToad3)
{
	[Style right]
	Do you want to borrow more?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BorrowToad4)
{
	[Next]
	Good luck! Don't forget to equip[BR]
	any badges you have![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad5)
{
	[Next]
	Sorry Mario...[BR]
	[Pause 10]You don't have any Star Pieces.[BR]
	[Pause 10]It's just too risky, I'm sure you'll[BR]
	do fine out there...
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad6)
{
	[Style right]
	Sorry Mario.[BR]
	[Wait][Next]
	But I don't have any more[BR]
	Badges to lend to you.[BR]
	[Pause 10]Good luck![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad7)
{
	[Next]
	Which Badges do you want to[BR]
	borrow?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad8)
{
	[Style right]
	Changed your mind eh?[BR]
	[Pause 10]No problem![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad9)
{
	[Style right]
	You want to borrow[BR]
	"[Var 0]" for[BR]
	[Var 1] Star Pieces.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BorrowToad10)
{
	[Next]
	Changed your mind huh?[BR]
	[Pause 10]Take your time.[BR]
	[Wait][Next]
	Alright. Do you want to borrow a[BR]
	different Badge?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad11)
{
	[Style right]
	Good choice Mario![BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BorrowToad12)
{
	[Style right]
	Mario.[BR]
	[Pause 10]I still have some Badges.[BR]
	You could borrow.[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BorrowToad13)
{
	[Next]
	You don't want to borrow more[BR]
	Badges?[BR]
	[Wait][Next]
	No problem! The less risk for me,[BR]
	the better![BR]
	[Wait][Next]
	Although you can borrow more[BR]
	if you want to...[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT1)
{
	[Style right]
	Oh, hi there Mario! [HEART][BR]
	[Wait][Next]
	I'm terribly busy at the moment,[BR]
	I'm afraid I can't cook you[BR]
	anything![BR]
	[Wait][Next]
	Would you like to look through the[BR]
	day's leftovers?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BuyTayceT2)
{
	[Style right]
	You want to take[BR]
	"[Var 0]" for[BR]
	[Var 1] Coins.[BR]
	[Wait][Next]
	Do you want this one?[BR]
	[Yield][End]
}




#message:2F:(TrainLobby_BuyTayceT3)
{
	[Style right]
	Do you want to buy more?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BuyTayceT4)
{
	[Next]
	Goodbye! Be careful and eat[BR]
	slowly![HEART][BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT5)
{
	[Next]
	Sorry Mario...[BR]
	[Pause 10]You don't have any Coins.[BR]
	[Pause 10]I can't give both you and your[BR]
	brother a tab today.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT6)
{
	[Style right]
	I'm sorry Mario![BR]
	[Wait][Next]
	But we don't have any more[BR]
	leftovers at the moment.[BR]
	[Pause 10]Good luck Mario!
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT7)
{
	[Next]
	Which leftovers do you want to[BR]
	take?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT8)
{
	[Style right]
	Not your taste huh?[BR]
	[Pause 10]It's okay I understand.[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT9)
{
	[Style right]
	You want to buy[BR]
	"[Var 0]" for[BR]
	[Var 1] Coins.[BR]
	[Wait][Next]
	Is this what you want?[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BuyTayceT10)
{
	[Next]
	Changed your mind huh?[BR]
	[Pause 10]Take your time.[BR]
	[Wait][Next]
	Alright. Do you want to buy a[BR]
	different leftover?[BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT11)
{
	[Style right]
	Thanks for shopping here[BR]
	Mario! [HEART][BR]
	[Wait][End]
}



#message:2F:(TrainLobby_BuyTayceT12)
{
	[Style right]
	Oh Mario![BR]
	[Pause 10]I still have some leftovers.[BR]
	[Yield][End]
}



#message:2F:(TrainLobby_BuyTayceT13)
{
	[Next]
	You don't want anymore[BR]
	leftovers?[BR]
	[Wait][Next]
	Well. That's fine! I can probably[BR]
	sell the rest later.[BR]
	[Wait][Next]
	Please feel free to shop with me[BR]
	anytime!
	[Wait][End]
}


#message:2F:(TrainHeist_GreenBattleStart)
{
	[Style Right]
	This it men![BR]
	[Wait][Next]
	Get the cannons ready![Pause 10][BR]
	He's going to fight us![BR]
	[Wait][Next]
	Give it your all![BR]
	[Wait][End]
}


#message:2F:(TrainHeist_YellowBattleStart)
{
	[Style Right]
	Good luck making it over here[BR]
	now![BR]
	[Wait][Next]
	We haven't fed this bad boy all[BR]
	day, I bet to him you look mighty[BR]
	tasty right now...[BR]
	[Wait][End]
}


#message:2F:(TrainHeist_BlackBattleStart)
{
	[Style Right]
	We've got the law on our side[BR]
	Mario, give it up![BR]
	[Wait][Next]
	You'll be in a jail cell before the[BR]
	Angry Sunrise![BR]
	[Wait][End]
}


#message:2F:(TrainHeist_RedBattleStart)
{
	[Style Inspect]
	(Where's the dynamite?)[BR]
	[Wait][Next]
	(Is this a bowling ball?)[BR]
	[Wait][Next]
	(Lousy rat scammed me again...)[BR]
	[Wait][End]
}
